ALTER TABLE usuarios
ADD COLUMN role VARCHAR(50) NOT NULL,
ADD COLUMN nombre VARCHAR(100) NOT NULL,
ADD COLUMN apellido VARCHAR(100) NOT NULL,
ADD COLUMN email VARCHAR(150) NOT NULL,
ADD COLUMN date_time DATETIME NOT NULL;